name: PR

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'

jobs:
  lint:
    name: Clippy linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          call: lint
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        with:
          call: fmt
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"

  versionConflict:
    name: Cargo version conflict
    if: startsWith(github.event.pull_request.title, 'release:')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dagger/dagger-for-github@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          call: check-version-conflict --gh-auth-token env://GITHUB_TOKEN
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"
